//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HandySignatur.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HandySignatur.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;csr:processAuthenticationCSRRequest xmlns:csr=&quot;http://www.e-zustellung.at/namespaces/ed_remote_control_init_20150115&quot;
        ///                                     xmlns:dsig=&quot;http://www.w3.org/2000/09/xmldsig#&quot;
        ///                                     xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///                                     &gt;
        ///  &lt;!--&lt;dsig:Signature&gt;&lt;/dsig:Signature&gt;--&gt;
        ///  &lt;csr:MandateEdid&gt;&lt;/csr:MandateEdid&gt;
        ///  &lt;csr:validForYears&gt;P1Y&lt;/csr:validForYears&gt;
        ///  &lt;cs [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string EmptyCSRRequest {
            get {
                return ResourceManager.GetString("EmptyCSRRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding =&quot;utf-8&quot;?&gt;
        ///&lt;sl:CreateXMLSignatureRequest xmlns:sl=&apos;http://www.buergerkarte.at/namespaces/securitylayer/1.2#&apos; xmlns:dsig=&apos;http://www.w3.org/2000/09/xmldsig#&apos;&gt;
        ///  &lt;sl:KeyboxIdentifier&gt;SecureSignatureKeypair&lt;/sl:KeyboxIdentifier&gt;
        ///  &lt;sl:DataObjectInfo Structure=&apos;detached&apos;&gt;
        ///    &lt;sl:DataObject Reference=&apos;&apos;/&gt;
        ///    &lt;sl:TransformsInfo&gt;
        ///      &lt;dsig:Transforms&gt;
        ///        &lt;dsig:Transform Algorithm=&apos;http://www.w3.org/2000/09/xmldsig#enveloped-signature&apos;/&gt;
        ///      &lt;/dsig:Transforms&gt;
        ///       [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string XMLSignRequest {
            get {
                return ResourceManager.GetString("XMLSignRequest", resourceCulture);
            }
        }
    }
}
