//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eZustellSendPOC.RCSInit {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.e-zustellung.at/namespaces/ed_remote_control_init_20150115")]
    public partial class FaultType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FaultReasonType reasonField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FaultReasonType Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
                this.RaisePropertyChanged("Reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34230")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.e-zustellung.at/namespaces/ed_remote_control_init_20150115")]
    public enum FaultReasonType {
        
        /// <remarks/>
        AUTHENTICATION_FAILURE,
        
        /// <remarks/>
        ILLEGAL_STATE,
        
        /// <remarks/>
        INVALID_SIGNATURE,
        
        /// <remarks/>
        INVALID_XML_REQUEST,
        
        /// <remarks/>
        INVALID_CSR,
        
        /// <remarks/>
        INTERNAL_ERROR,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.e-zustellung.at/namespaces/ed_remote_control_init_20150115", ConfigurationName="RCSInit.RemoteControlInit")]
    public interface RemoteControlInit {
        
        // CODEGEN: Der Nachrichtenvertrag wird generiert, da der Vorgang register weder in RPC noch in einem Dokument eingeschlossen ist.
        [System.ServiceModel.OperationContractAttribute(Action="register", ReplyAction="http://www.e-zustellung.at/namespaces/ed_remote_control_init_20150115/RemoteContr" +
            "olInit/registerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(eZustellSendPOC.RCSInit.FaultType), Action="http://www.e-zustellung.at/namespaces/ed_remote_control_init_20150115/RemoteContr" +
            "olInit/register/Fault/RemoteControlInitFault", Name="RemoteControlInitFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eZustellSendPOC.RCSInit.registerResponse register(eZustellSendPOC.RCSInit.registerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="register", ReplyAction="http://www.e-zustellung.at/namespaces/ed_remote_control_init_20150115/RemoteContr" +
            "olInit/registerResponse")]
        System.Threading.Tasks.Task<eZustellSendPOC.RCSInit.registerResponse> registerAsync(eZustellSendPOC.RCSInit.registerRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.e-zustellung.at/namespaces/ed_remote_control_init_20150115", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] processAuthenticationCSR;
        
        public registerRequest() {
        }
        
        public registerRequest(byte[] processAuthenticationCSR) {
            this.processAuthenticationCSR = processAuthenticationCSR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.e-zustellung.at/namespaces/ed_remote_control_init_20150115", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] processAuthenticationCSRResponse;
        
        public registerResponse() {
        }
        
        public registerResponse(byte[] processAuthenticationCSRResponse) {
            this.processAuthenticationCSRResponse = processAuthenticationCSRResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RemoteControlInitChannel : eZustellSendPOC.RCSInit.RemoteControlInit, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RemoteControlInitClient : System.ServiceModel.ClientBase<eZustellSendPOC.RCSInit.RemoteControlInit>, eZustellSendPOC.RCSInit.RemoteControlInit {
        
        public RemoteControlInitClient() {
        }
        
        public RemoteControlInitClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RemoteControlInitClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteControlInitClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RemoteControlInitClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eZustellSendPOC.RCSInit.registerResponse eZustellSendPOC.RCSInit.RemoteControlInit.register(eZustellSendPOC.RCSInit.registerRequest request) {
            return base.Channel.register(request);
        }
        
        public byte[] register(byte[] processAuthenticationCSR) {
            eZustellSendPOC.RCSInit.registerRequest inValue = new eZustellSendPOC.RCSInit.registerRequest();
            inValue.processAuthenticationCSR = processAuthenticationCSR;
            eZustellSendPOC.RCSInit.registerResponse retVal = ((eZustellSendPOC.RCSInit.RemoteControlInit)(this)).register(inValue);
            return retVal.processAuthenticationCSRResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eZustellSendPOC.RCSInit.registerResponse> eZustellSendPOC.RCSInit.RemoteControlInit.registerAsync(eZustellSendPOC.RCSInit.registerRequest request) {
            return base.Channel.registerAsync(request);
        }
        
        public System.Threading.Tasks.Task<eZustellSendPOC.RCSInit.registerResponse> registerAsync(byte[] processAuthenticationCSR) {
            eZustellSendPOC.RCSInit.registerRequest inValue = new eZustellSendPOC.RCSInit.registerRequest();
            inValue.processAuthenticationCSR = processAuthenticationCSR;
            return ((eZustellSendPOC.RCSInit.RemoteControlInit)(this)).registerAsync(inValue);
        }
    }
}
